---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TransactionsLogTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: user
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: N
      KeySchema:
      - AttributeName: user
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "transactions_log"
    Type: AWS::DynamoDB::Table
Outputs:
  TransactionsLogTable:
    Description: Table for rewarding logs.
    Value:
      Ref: TransactionsLogTable
