frameworkVersion: '3'
service: banker

resources:
  Resources:
    TransactionsLogTable:
      Properties:
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: user
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'transactions_log'
      Type: AWS::DynamoDB::Table
  Outputs:
    TransactionsLogTable:
      Description: Table for rewarding logs.
      Value:
        Ref: TransactionsLogTable
    TransactionsLogTableArn:
      Description: The ARN of the table.
      Value: { 'Fn::GetAtt': ['TransactionsLogTable', 'Arn'] }
      Export:
        Name: TransactionsLogTableArn

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  stage: ${opt:stage, 'dev'}
  timeout: 10
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            Fn::GetAtt:
              - TransactionsLogTable
              - Arn

functions:
  message:
    handler: handler.message
    events:
      - http:
          path: api/message
          method: post
          cors: true
    environment:
      LOG_TABLE_NAME: transactions_log
      MAX_POINT_PER_DAY: ${file(../../.config.${self:provider.stage}.yml):MAX_POINT_PER_DAY}
      REACT_SYMBOL: ${file(../../.config.${self:provider.stage}.yml):REACT_SYMBOL}
      REACT_NEGATIVE_SYMBOL: ${file(../../.config.${self:provider.stage}.yml):REACT_NEGATIVE_SYMBOL}
      REWARD_SYMBOL: ${file(../../.config.${self:provider.stage}.yml):REWARD_SYMBOL}
      REWARD_NAME: ${file(../../.config.${self:provider.stage}.yml):REWARD_NAME}
      REWARD_PLURAL: ${file(../../.config.${self:provider.stage}.yml):REWARD_PLURAL}
      CLIENT_SIGNING_SECRET: ${file(../../.config.${self:provider.stage}.yml):CLIENT_SIGNING_SECRET}
      CLIENT_ID: ${file(../../.config.${self:provider.stage}.yml):CLIENT_ID}
      CLIENT_SECRET: ${file(../../.config.${self:provider.stage}.yml):CLIENT_SECRET}
      BOT_TOKEN: ${file(../../.config.${self:provider.stage}.yml):BOT_TOKEN}
      VERIFICATION_TOKEN: ${file(../../.config.${self:provider.stage}.yml):VERIFICATION_TOKEN}
      STAGE: ${file(../../.config.${self:provider.stage}.yml):STAGE}

# Auto rotation
plugins:
  - serverless-prune-plugin
custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
